### ISSUE TITLE
Quick_ACG project is broken

### ISSUE THREAD

**Issue by anatolii-bohdanov** [docusign/code-examples-csharp#34]
IDE: Visual Studio 2022
Solution: Quick_ACG
OS: Windows 11

I used this article https://developers.docusign.com/docs/esign-rest-api/quickstart/ to generate the code.

In both "Authorization Code Grant embedded signing example" and "Multiple code examples, Authorization Code Grant and JWT Grant" scenarios Quick ACG project is not working.

In "**Authorization Code Grant embedded signing example**" scenario the build is failing with error 
```
Source file 'C:\s\Quickstart App-1-c#\Quick_ACG\..\launcher-csharp\eSignature\Controllers\EmbeddedSigningCeremony.cs' could not be found.
```

In "**Multiple code examples, Authorization Code Grant and JWT Grant**" scenario I receive this error in runtime
```
System.InvalidOperationException: The view 'quickEmbeddedSigning' was not found. The following locations were searched:
/Areas/eSignature/Views/EmbeddedSigningCeremony/quickEmbeddedSigning.cshtml
/Areas/eSignature/Views/Shared/quickEmbeddedSigning.cshtml
/Views/Shared/quickEmbeddedSigning.cshtml
/Pages/Shared/quickEmbeddedSigning.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by DSDemo-LeandroReis** [comment]
Hi anatolii-bohdanov,

I just made a test downloading the quick start app from the quick start page and had no issues with it. I was able to send an envelope with no issues whatsoever. I used Visual Studio 2022 and the "Multiple code examples, Authorization Code Grant, and JWT Grant" package. My Windows version is 10.

In the [quick start overview](https://developers.docusign.com/docs/esign-rest-api/quickstart/overview/) you have a section named "Configuration and setup" where you can pick your SDK language and go through some steps to setup your environment. Have you done that?

Make sure you have all the prerequisites and that you follow the steps to run the quick start and you should have no issues. If you're still having problems, download a new copy and give it a new try.

Please let me know the results of your tests.

Kindly,
Leandro Reis - DocuSign Developer Support

**Comment by InbarGazit** [comment]
Sorry, we're going to fix this ASAP

**Comment by InbarGazit** [comment]
@anatolii-bohdanov  the issue was fixed, but with the caveat that we still need to fix quickstart to retrieve the right set of files as one of the files was renamed.
If you close the whole repo, than you should be able to runt he Quick_ACG project now, please confirm

**Comment by InbarGazit** [comment]
This should be fixed
